title: My blog
email: lavoiecsh@gmail.com
description: >
  A blog about programming<br/>
  Un blog à propos de la programmation<br/>
  Sébastien Lavoie-Courchesne
baseurl: ''
url: http://lavoiecsh.github.io/
twitter_username: 
github_username:  lavoiecsh
markdown: kramdown

