# Site settings
title: My blog
email: lavoiecsh@gmail.com
description: >
  A simple programming blog by/Un blog de programmation simple par Sébastien Lavoie-Courchesne.
baseurl: ""
url: "http://lavoiecsh.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  lavoiecsh

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine