using Xunit;

namespace advent.util.test
{
    public class Day17ClayFileReaderDataProviderTest
    {
        [Fact]
        public void ReturnsMapOfClayInFile()
        {
            const string filename = "data\\day17_clay.txt";
            const string expectedMap = @"......+.......
............#.
.#..#.......#.
.#..#..#......
.#..#..#......
.#.....#......
.#.....#......
.#######......
..............
..............
....#.....#...
....#.....#...
....#.....#...
....#######...
";
            var map = new Day17ClayFileReaderDataProvider(filename).GetData().ToString();
            Assert.Equal(expectedMap, map);
        }
    }
}